### ISSUE TITLE
Crawler fails

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pyPavics#20]
```
out = thredds_crawler('http://pavics.ouranos.ca/thredds', index_facets=['project'], target_files='birdhouse/nrcan')
``` 
fails (after a very long time) with 
```
ConnectionError: HTTPSConnectionPool(host='pavics.ouranos.ca', port=443): Max retries exceeded with url: /thredds/catalog/birdhouse/wps_outputs/flyingpigeon/ebddf1e8-28ee-11e8-9f13-0242ac12000d/catalog.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb449adb5d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
In principle, it should not go there because I specified target_files.

**Comment by ldperron** [comment]
Maybe the same root cause, but this error also occurs: ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer')), when the crawler is started using:
curl 'http://boreas.ouranos.ca:8086/pywps?service=WPS&request=execute&version=1.0.0&identifier=pavicrawler&storeExecuteResponse=true&status=true&DataInputs='

**Comment by ldperron** [comment]
Identified the root cause of the pavicrawler issue on Boreas: While the crawl is checking for replicas, Boreas is running out of ephemeral ports.

**Comment by tomLandry** [comment]
So esoteric, so specific, so alien-sounding. I love it.

**Comment by ldperron** [comment]
Especially hard to debug when the issue happens 16 hours after the crawler has be launched.
I sent an e-mail to Mourad, because root access is required to change a system setting on Boreas:
sysctl -w net.ipv4.tcp_tw_reuse=1

**Comment by tomLandry** [comment]
"We choose to go to the *Earth*! We choose to go to the *Earth* in this decade and do the other things, not because they are easy, but because they are **hard**; because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one we intend to win, and the others, too." -JFK

**Comment by huard** [comment]
Trop de café ce matin Tom?

**Comment by Zeitsperre** [comment]
"Earth provides for every man's need, not every man's greed" - Mahatma Gandhi

**Comment by ldperron** [comment]
The sysctl change will do the trick. This should be documented in PAVICS installation.

**Comment by dbyrns** [comment]
@ldperron maybe you could do a PR on that : https://github.com/Ouranosinc/pavics-sdi/blob/master/docs/source/dev/installation.rst
This is the "official" pavics documentation

**Comment by ldperron** [comment]
Crawler currently running... results tomorrow.

**Comment by dbyrns** [comment]
Good catch @ldperron, that was a tough one.

**Comment by ldperron** [comment]
Added a warning in pavics-compose.sh https://github.com/Ouranosinc/PAVICS/commit/f6e58b5c02a9f287cacf3654545377320dbed98e

**Comment by huard** [comment]
Closeable ?

**Comment by ldperron** [comment]
Yup... I just noticed that "closed" and "done" are not the same.
